/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    FileList: typeof import('./components/FileList.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Movies: typeof import('./components/Movies.vue')['default']
    MoviesPage: typeof import('./components/MoviesPage.vue')['default']
    MovieSuggestions: typeof import('./components/MovieSuggestions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./components/Upload.vue')['default']
    VideoPlayer: typeof import('./components/VideoPlayer.vue')['default']
    Watch: typeof import('./components/Watch.vue')['default']
  }
}
