/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/FileListPage': RouteRecordInfo<'/FileListPage', '/FileListPage', Record<never, never>, Record<never, never>>,
    '/MoviesPage': RouteRecordInfo<'/MoviesPage', '/MoviesPage', Record<never, never>, Record<never, never>>,
    '/MovieSuggestionsPage': RouteRecordInfo<'/MovieSuggestionsPage', '/MovieSuggestionsPage', Record<never, never>, Record<never, never>>,
    '/VideoPlayerPage': RouteRecordInfo<'/VideoPlayerPage', '/VideoPlayerPage', Record<never, never>, Record<never, never>>,
    '/WatchPage': RouteRecordInfo<'/WatchPage', '/WatchPage', Record<never, never>, Record<never, never>>,
  }
}
